FROM python:3.7-alpine

WORKDIR /app
COPY requirements/base.txt .

# essential for setting up connection for postgres

RUN apk add postgresql-dev gcc python3-dev musl-dev
RUN apk --update add libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev

RUN pip install -r base.txt

# Add entrypoint script
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh

COPY ./ ./

EXPOSE 8990

ENTRYPOINT ["entrypoint.sh"]

WORKDIR /app

CMD ["python", "manage.py", "runserver", "0.0.0.0:8990", "--settings=django_project.settings.test"]